### ISSUE TITLE
[trusty] Varnish key needs to be bigger

### ISSUE THREAD

**Issue by googletorp** [computerminds/parrot#100]
```Warning: /Apt_key[Add key: C4DEFFEB from Apt::Source varnish]: The id should be a full fingerprint (40 characters), see README.```

**Comment by googletorp** [comment]
So this is the ID for the varnish GPG-key that needs to be a full fingerprint

**Comment by darthsteven** [comment]
Yep, any idea what the full fingerprint is?

**Comment by googletorp** [comment]
I found it, one less error
