### ISSUE TITLE
[trusty] Support PHP 7

### ISSUE THREAD

**Issue by googletorp** [computerminds/parrot#105]
PHP 7 is only at RC 6 now I believe, but it will be ready soon with big performance gains for Drupal 8 sites. We should definately support this once it's ready, as most people doing Drupal 8 development want to do this on PHP 7.

**Comment by darthsteven** [comment]
Agreed!

**Comment by darthsteven** [comment]
I reckon we use the same php_version variable we had before, and just support 7.0 in addition to the default, 5.5 and 5.6.

**Comment by googletorp** [comment]
@darthsteven  For trusty we are currently using [nodes-php](http://puppet-php.readthedocs.org) to install PHP. We might be able to install different versions of PHP 5, but nodes-php doesn't support PHP 7 (for now). We would need an entirely different tool for installing PHP unless nodes-php adds support for this.

**Comment by darthsteven** [comment]
Oh pants, are you sure? I thought that nodes-php just installed PHP from the package managers packages and left versioning to that?

**Comment by googletorp** [comment]
I'm not 100% sure, but there seems to be a lot of things tied up to `php5` as it's mentioned a lot of times inside the nodes-php module. I might not be an issue, but I would be surprised. PHP 5.5 / 5.6 should be straight forward

**Comment by darthsteven** [comment]
Oh, sure thing then.

**Comment by darthsteven** [comment]
Support is now in the trusty branch.
