### ISSUE TITLE
[trusty] parrot-local.ini is ignored

### ISSUE THREAD

**Issue by tripox** [computerminds/parrot#111]
Editing 'parrot-local.ini' doesn't change the content in '/etc/php5/fpm/php.ini' after running 'vagrant provision'

**Comment by darthsteven** [comment]
:( Does it just need to restart php5-fpm?

**Comment by tripox** [comment]
Nope, looks like it doesn't change at all. :-1: :/

**Comment by darthsteven** [comment]
Ah fun times.

Right, let's look at this.

**Comment by darthsteven** [comment]
Added support for this back in in #125
