### ISSUE TITLE
The trusty branch installs PHP7

### ISSUE THREAD

**Issue by tripox** [computerminds/parrot#126]
Just cloned parrot and made a checkout on the trusty branch.
When I run vagrant up it installs PHP7, even though .parrot-php7 doesn't exist.

**Comment by darthsteven** [comment]
Yep, this is as designed.

PHP 5.6 and 7.0 run alongside each other now.

**Comment by tripox** [comment]
Oh, sorry. :)
I thought you had to create a file called .parrot-php7 and run 'vagrant provision' before it would use PHP 7 and then thought it would use PHP 5.6 as default if that file didn't exist.
