### ISSUE TITLE
Xhprof output just displays file

### ISSUE THREAD

**Issue by anotherjames** [computerminds/parrot#129]
i.e. on visiting http://localhost/xhprof/index.php, my browser just shows me the contents of that file rather than running the PHP!

**Comment by darthsteven** [comment]
What version (git commit) of parrot are you using?

**Comment by anotherjames** [comment]
I'm currently on c4e30a8d3775e6c68cc211fc94b76da5d0251f10 on trusty.

**Comment by anotherjames** [comment]
Oh, am I just out of date?

**Comment by darthsteven** [comment]
Yeah, sort of, xhprof is removed at the moment, adding it back in #124 and probably need to resolve phpMyAdmin too in #120

**Comment by darthsteven** [comment]
Yeah, so I think this issue is just a duplicate of #120.
